<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>CleanArchitecture.Web.AcceptanceTests</RootNamespace>
        <AssemblyName>CleanArchitecture.Web.AcceptanceTests</AssemblyName>
        <ReqnrollUseIntermediateOutputPathForCodeBehind>true</ReqnrollUseIntermediateOutputPathForCodeBehind>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.Playwright" />
        <PackageReference Include="Reqnroll.NUnit" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="nunit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.Logging" />
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Web\Web.csproj" />
    </ItemGroup>

</Project>
