-- Initial schema: TodoLists/TodoItems.
-- Users and roles are owned by Keycloak, not this database — CreatedBy/LastModifiedBy
-- store the Keycloak user id (the "sub" claim) as a plain string, no local user table.
-- Scripts in this folder are applied in order (by filename) by DbUp and
-- recorded in the SchemaVersions journal table. Never edit a script once
-- it has shipped — add a new numbered script instead.

CREATE TABLE "TodoLists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Colour_Code" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text NULL,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text NULL,
    CONSTRAINT "PK_TodoLists" PRIMARY KEY ("Id")
);

CREATE TABLE "TodoItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Note" text NULL,
    "Priority" integer NOT NULL,
    "Done" boolean NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text NULL,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text NULL,
    CONSTRAINT "PK_TodoItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TodoItems_TodoLists_ListId" FOREIGN KEY ("ListId") REFERENCES "TodoLists" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TodoItems_ListId" ON "TodoItems" ("ListId");
