-- App-side audit log of administrative changes (users and roles). Keycloak's admin events
-- would attribute every change to the app's service account, so the app records the real
-- administrator here instead. Entries are append-only.

CREATE TABLE "AuditEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NOT NULL,
    "ActorId" text NULL,
    "ActorName" character varying(256) NULL,
    "Action" character varying(64) NOT NULL,
    "TargetType" character varying(32) NOT NULL,
    "TargetId" text NULL,
    "TargetName" character varying(256) NULL,
    "Details" text NULL,
    CONSTRAINT "PK_AuditEntries" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_AuditEntries_Timestamp" ON "AuditEntries" ("Timestamp");
